### PR TITLE
corrected ack seq

### PR DESCRIPTION
**Pull request by timsaxe**
pulp-freertos was hanging when accessing the dummy FLLs.  apb_fll_if expects a 4 cycle handshake: assert req, assert ack, deassert req, deassert ack.  The dummy (FPGA) FLL simply asserted ack all the time, which means the state machine hung in phase 2.

I have tested the fix on nexysA7-100T.  The RTL looks identical on all of the platforms (might be preferable to have a Xilinx directory that all Xilinx boards referred to) so I replaced all of them.  The test consists of using gdb to observe that multiple reads of the FLL registers don't hang.  The actual application, hello_world_pmsis, does not function correctly which suggests there is some other issue to be resolved.

### CODE REVIEW

**Comment by bluewww** [comment]
@timsaxe thanks for the pr.

I dont' think it makes sense for adding your quick logic specific techcells though. The reposititories are even private.

Also the FLL access is a pulp-freertos bug which I track here https://github.com/pulp-platform/pulp-freertos/issues/1

**Comment by timsaxe** [comment]
Oh interesting.  I agree that you don't want those two commits.  I did them after the PR, so I didn't realize they would be included. Now I need to think about a cleaner way to handle them.

**Comment by bluewww** [comment]
Oh I see. I suggest you make a fresh branch (e.g. `for-pulpissimo`)  instead of using `master` in a PR.

**Comment by bluewww** [comment]
Thanks for PR. I close this one since it has further commits that don't belong to the PR. I extracted your fix into https://github.com/pulp-platform/pulpissimo/pull/206

**Comment by timsaxe** [comment]
Great.  Thanks.

**Pull request closed without merging**
