### PR TITLE
Added ZedBoard FPGA board support

### PR DESCRIPTION
**Pull request by MarekPikula**

### CODE REVIEW

**Comment by meggiman** [comment]
Hi @MarekPikula 

First of all: Thanks a lot for your contribution. I just checkout your branch in order to test the bitstream flow for the new board. When I tried to generate the bitstream for the Zedboard I got a placement error (see below). I used Vivado 2018.3 running the zedboard make target. Did you also experience that problem and if not, what version of Vivado where you using?

Greetings,
Manuel
 
```
[Place 30-575] Sub-optimal placement for a clock-capable IO pin and MMCM pair. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
	< set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets ref_clk] >

	i_sysclk_iobuf (IBUF.O) is locked to IOB_X0Y26
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/mmcm_adv_inst (MMCME2_ADV.CLKIN1) is provisionally placed by clockplacer on MMCME2_ADV_X0Y0
	 i_pulpissimo/soc_domain_i/pulp_soc_i/i_clk_rst_gen/i_fpga_clk_gen/i_clk_manager/inst/mmcm_adv_inst (MMCME2_ADV.CLKIN1) is provisionally placed by clockplacer on MMCME2_ADV_X1Y0

	The above error could possibly be related to other connected instances. Following is a list of 
	all the related clock rules and their respective instances.

	Clock Rule: rule_mmcm_bufg
	Status: PASS 
	Rule Description: An MMCM driving a BUFG must be placed on the same half side (top/bottom) of the device
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/mmcm_adv_inst (MMCME2_ADV.CLKFBOUT) is provisionally placed by clockplacer on MMCME2_ADV_X0Y0
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/clkf_buf (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y1

	Clock Rule: rule_mmcm_bufhce
	Status: PASS 
	Rule Description: An MMCM driving a BUFH must both be in the same horizontal row (clockregion-wise)
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/mmcm_adv_inst (MMCME2_ADV.CLKOUT0) is provisionally placed by clockplacer on MMCME2_ADV_X0Y0
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/clkout1_buf_en (BUFH.I) is provisionally placed by clockplacer on BUFHCE_X0Y0

	Clock Rule: rule_bufh_bufr_ramb
	Status: PASS 
	Rule Description: Reginal buffers in the same clock region must drive a total number of brams less
	than the capacity of the region
	 i_pulpissimo/safe_domain_i/i_slow_clk_gen/i_slow_clk_mngr/inst/clkout1_buf_en (BUFH.O) is provisionally placed by clockplacer on BUFHCE_X0Y0

	Clock Rule: rule_mmcm_bufg
	Status: PASS 
	Rule Description: An MMCM driving a BUFG must be placed on the same half side (top/bottom) of the device
	 i_pulpissimo/soc_domain_i/pulp_soc_i/i_clk_rst_gen/i_fpga_clk_gen/i_clk_manager/inst/mmcm_adv_inst (MMCME2_ADV.CLKFBOUT) is provisionally placed by clockplacer on MMCME2_ADV_X1Y0
	 and i_pulpissimo/soc_domain_i/pulp_soc_i/i_clk_rst_gen/i_fpga_clk_gen/i_clk_manager/inst/clkf_buf (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y2
```

**Comment by MarekPikula** [comment]
I'm using the most recent one. From what I recall 2019.1. To be honest I just ran the test to check if everything is generating and I don't recall seeing errors, but I might have overlooked something as either way I'm using slightly modified version of PULPissimo in my project. I will look into that tomorrow.

**Comment by MarekPikula** [comment]
Indeed it fails on me too. I don't know how I didn't notice before.

**Comment by MarekPikula** [comment]
To be honest I don't really know how to address this issue correctly. After my last commit it builds without error, but I have a feeling that setting `ref_clk` as `CLOCK_DEDICATED_ROUTE FALSE` is not particularly good idea.

Maybe it doesn't matter that much since the clock used by SoC is synthesized by PLL, so `ref_clk` has pretty much only two fanouts (`slow_clk_gen` and `clk_manager`), but I'm always a little bit sceptical with using this flag on main system clock.

Maybe you have some suggestions what could be done in terms of constraints that would help mitigating this issue?

**Comment by MarekPikula** [comment]
Ok, I've found the issue. I'll update the PR tomorrow.

**Comment by MarekPikula** [comment]
Updated with working version based on current master.

The issue with clock was there, because somehow `CLOCK_DEDICATED_ROUTE FALSE` wasn't set for JTAG TCK, so Vivado took TCK as main clock, not `ref_clk`.

**Comment by meggiman** [comment]
Hi MarekPikula,

Thanks for the update. I will try it out and merge it if everything works fine (luckily I do have a Zedboard at hand).

As general advice, setting CLOCK_DEDICATED_ROUTE to FALSE is not something you should do carelessly as TCK is in fact a clock that drives the clk pins of the sequential logic in the JTAG module. It doesn't matter whether one considers the signal to be the main clock of the system. As soon as it acts as the clock for sequential logic it should be routed with dedicated clock routes on the FPGA. Otherwise the insertion delay until the signal arrives at the BUFG is unpredictable.

However, in this case, you might be right in that this seems to be the only way to make PULPIssimo map to the Zynq-7000 which doesn't have as many clock ressources as other, larger FPGAs e.g. Virtex-7 series in the other FPGA boards that we support.

**Comment by MarekPikula** [comment]
Actually other boards have the same constraint, so I thought it's not a problem.

**Comment by meggiman** [comment]
You are right :-) It seems like I overlooked it while merging the ZCU104 port.

**Comment by meggiman** [comment]
Thanks again for your contribution

**Pull request merged**
